# -*- coding: utf-8 -*-
"""Lab_2_AlgorithmsBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEi9wIZfjjxtaHUdyg0MKcqd5al3_W4j

# LAB_2. Algorithm's Basics

#1.1 Problem Definition
This file contains a series of programming exercises designed for practice and understanding of recursion, time complexity, and array/list manipulation task. Your task is to: 1. Write in the form of comment what each function does. 2. Calculate the time complexity of each function. A Sample example is given in Exercie 1
"""

# Exercise 1
def func1(a, b):
  result = 0
  for i in range(0, b):
    result += a
  return result

# Sample function call: func1(5, 3)
x=print(func1(4,3))
#the function performs multiplication using repeated addition

# Exercise 2
def func2(a, b):
  result = 1
  while b > 0:
    result = result * a
    b = b - 1
  return result

# Sample function call: func2(2, 4)
X = print(func2(2,4))
# the function performs exponentian of a to b using repeated multiplication

# Exercise 3
def func3(num):
   result = 0
   while num>0:
    result = result + num % 10
    num= num//10
    return result

# Sample function call: func3(1234)
x = print(func3(1234))
# the result part removes the last digit and the num part removes the fractional part till num is not 0.

# Exercise 4
def func4(a, b):
    b.sort() # Time complexity for this function is O(Nlog N) where N = len(b)
    intersect = 0
    for x in a:
        if binary_search(b, x) >= 0:
            intersect = intersect + 1
    return intersect

def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

# Sample function call: func4([1, 2, 3, 4], [2, 4, 6, 8])
x = print(func4([1, 2, 3, 4], [2, 4, 6, 8]))
# this function performs binary search.

# Exercise 5
def func5(n):
    guess = 1
    while guess * guess <= n:
        if guess * guess == n:
            return guess
        guess = guess + 1
    return None

# Sample function call: func5(16)
x = print(func5(16))
#returns the guess when its square is equal to the given number if not then it increments it by 1.

# Exercise 6
def func8(A):
    func8_helper(A, 0, len(A) -1)

def func8_helper(A, i, j):
    #Input: An array A and two indices i and j.
    n = j - 1 + 1
    if n ==2:
        if A[i] > A[j]:
            # Swap A[i] and A[j]
            A[i], A[j] = A[j], A[i]
        elif n > 2:
            m = n // 3
            func8_helper(A, i, j - m)
            func8_helper(A, i + m, j)
            func8_helper(A, i, j - m)
        return A

#Sample function call: func8([3,1,2,7,8,6])
x = print(func8_helper([3,1,2,7,8,6]))

# Exercise 7
def func12(arr, k):
    arr_len = len(arr)
    k = k % arr_len
    # Initialize a new array of the same length as 'arr'
    custom_arr = [0] * arr_len

    for i in range(arr_len):
        mystery_index = (i + k) % arr_len
        custom_arr[mystery_index] = arr[i]
    return custom_arr

#Sample function call: func12([1, 2, 3, 4, 5], 2)
x = print(func12([1, 2, 3, 4, 5], 2))

"""##1.2 Arrays
Programs on 1-d arrays like - sum of elements of array, searching an element inarray, finding minimum and maximum element in array, count the number ofeven and odd numbers in array. For all such programs, also find the timeComplexity, compare if there are multiple methods
"""

# write a function named as sum_arr to find sum of elements in given array
def sum_arr(arr):
  sum=0
  for i in arr:
    sum+=i
  return sum

#call the function
arr = [12, 3, 4, 15,45,78,450]
print(sum_arr(arr))

#write a function named as max_min to find minimum (or maximum) element in an array
def max_min(arr):
  max=arr[0]
  min=arr[0]
  for i in arr:
    if i >max:
      max=i
    elif i <min:
      min=i
  return max,min

# call sum_arr to find sum of elements in given array for arr = [12, 1234, 45, 67, 1]
arr = [12, 1234, 45, 67, 1]
print(max_min(arr))

# write a function named as Counting_EvenOdd to count number of even and odd elements in an array
def Counting_EvenOdd(arr):
  count_even=0
  count_odd=0
  for i in arr:
    if i%2==0:
      count_even +=1
    else:
      count_odd +=1
      return count_even,count_odd

# call above function for arr = [2, 3, 4, 5, 6,7,8,9,10,11,12,13]
arr = [2, 3, 4, 5, 6,7,8,9,10,11,12,13]
print(Counting_EvenOdd(arr))

# write a function named as linear_Search to perform a linear search in 1D-array
def linear_Search(arr, x):
  for i in range(len(arr)):
    if arr[i]==x:
      return i
  return -1

# call the function liner_Search for array = [1, 3, 5, 7, 9]
arr = [1, 3, 5, 7, 9]
x = 9
print(linear_Search(arr, x))

# write a function named as Binary_Search to perform binary search in 1D-array
def Binary_Search(arr, x):
  low = 0
  high = len(arr)-1
  mid = 0
  while low <= high:
    mid = (high + low)//2
    if arr[mid]<x:
      low = mid+1
    elif arr[mid]>x:
      high = mid-1
    else:
        return mid
  return -1

# call the function Binary_Search for array arr = [1, 3, 5, 7, 9,15,16,14,45]
arr = [1, 3, 5, 7, 9,15,16,14,45]
x = 16
print(Binary_Search(arr, x))